ai_lab:
  target: dev
  outputs:
    dev:
      type: postgres
      host: connector
      user: "AIRFLOW_POSTGRES_USER"
      password: "AIRFLOW_POSTGRES_PASSWORD"
      port: 5432
      dbname: webshop_v2
      schema: webshop
      threads: 6
